#!/usr/bin/env bash
#
# Install dotfiles.
set -eo pipefail

install_pkg() {
  if test "$(which apt-get)"; then
    sudo apt-get install -y "$@"
  else
    brew install "$@"
  fi
}

check_dependencies() {
  for pkg in zsh git curl python python-pip pyp unzip  sudo; do
    if test ! "$(which $pkg)"; then
      install_pkg $pkg
    fi

    # curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh| zsh
  done
}

main() {
  if [ -d ~/.dotfiles ]; then
    echo "The '~/.dotfiles' folder already exists, please, backup it and run this again!"
    exit 1
  fi

  check_dependencies
  git clone --recursive https://github.com/moshe-immerman/dotfiles ~/.dotfiles
  cd ~/.dotfiles
  bash script/bootstrap
  chsh -s "$(which zsh)"
  echo "All done! Please, restart your terminal session!"
}
main
