#!/usr/bin/env bash
#
# Install dotfiles.
set -eo pipefail

brew install  zsh git curl python unzip
git clone --recursive https://github.com/moshloop/dotfiles ~/.dotfiles
cd ~/.dotfiles
chsh -s "$(which zsh)"
./script/bootstrap
git ls-tree --name-only -r HEAD | grep install.sh | while read -r installer; do
  echo "› ${installer}..."
  sh -c "$installer"
done